name: Deploy Strapi to AWS EC2

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: my-strapi-project

      - name: Terraform Plan
        run: terraform plan
        working-directory: my-strapi-project

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: my-strapi-project

      - name: Get EC2 Public IP
        id: getip
        run: |
          echo "PUBLIC_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

  deploy-strapi:
    needs: deploy-infra
    runs-on: ubuntu-latest
    steps:
      - name: Wait for EC2 readiness
        run: sleep 20

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy Docker image via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ env.PUBLIC_IP }} \
            'docker pull gayathri0315/strapi:latest && \
            docker stop strapi || true && \
            docker rm strapi || true && \
            docker run -d --name strapi -p 1337:1337 gayathri0315/strapi:latest'

      - name: Verify Deployment
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ env.PUBLIC_IP }} \
            'curl -f http://localhost:1337 || exit 1'
