name: Terraform Deploy (manual)

on:
  workflow_dispatch:
    inputs:
      image_full:
        description: 'Full ECR image (e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/myrepo:tag)'
        required: true

jobs:
  terraform:
    name: Terraform apply
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_INPUT: "false"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0' # change if you need a different version

      - name: Export TF env vars (pass secrets into Terraform as variables)
        run: |
          echo "TF_VAR_ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_region=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform fmt & validate
        run: terraform fmt && terraform validate

      - name: Terraform plan
        id: plan
        run: |
          terraform plan -input=false -var="image_full=${{ github.event.inputs.image_full }}" -out=tfplan

      - name: Show plan (optional)
        run: terraform show -no-color tfplan

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
