name: Terraform Deploy (manual)

on:
  workflow_dispatch:
    inputs:
      image_full:
        description: 'Full ECR image (e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/myrepo:tag)'
        required: true

jobs:
  terraform:
    name: Terraform apply
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_INPUT: "false"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show files (debug)
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f -name "*.tf" -print || true

      - name: Write SSH key to file and export TF_VAR path
        # This safely writes a multiline PEM to a file and exports the file path for Terraform
        run: |
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
          echo "TF_VAR_ssh_private_key=$(pwd)/id_rsa" >> $GITHUB_ENV
          echo "TF_VAR_aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_region=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "TF_VAR_vpc_id=${{ secrets.VPC_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_subnet_id=${{ secrets.SUBNET_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_key_name=${{ secrets.KEY_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_image_full=${{ github.event.inputs.image_full }}" >> $GITHUB_ENV
          echo "TF_VAR_instance_profile_name=${{ secrets.INSTANCE_PROFILE_NAME }}" >> $GITHUB_ENV  # <-- ADD THIS LINE
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Terraform fmt & validate
        working-directory: ./terraform
        run: terraform fmt && terraform validate

      - name: Terraform plan
        id: plan
        working-directory: ./terraform
        env:
          TF_VAR_instance_profile_name: ${{ secrets.INSTANCE_PROFILE_NAME }}
          TF_VAR_image_full: ${{ github.event.inputs.image_full }}
        run: terraform apply -auto-approve tfplan

      - name: Show plan (optional)
        working-directory: ./terraform
        run: terraform show -no-color tfplan

      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan

      - name: Cleanup TF plan file
        if: always()
        working-directory: ./terraform
        run: rm -f tfplan

      - name: Cleanup SSH key file
        if: always()
        run: rm -f id_rsa
